# Конфигурационный файл для viper-env-demo

# Настройки логирования
log:
  level: info
  format: console
  output: stdout
  caller: false
  timestamp: true
  pretty: true
  no_color: false

# Настройки сервера
server:
  host: localhost
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s
  tls:
    enabled: false
    cert_file: ""
    key_file: ""

# Настройки базы данных
database:
  driver: postgres
  host: localhost
  port: 5432
  database: viper_demo
  username: postgres
  password: ""
  max_connections: 25
  ssl_mode: prefer

# Настройки приложения
app:
  name: viper-env-demo
  version: 1.0.0
  environment: development
  debug: false
  features:
    - logging
    - metrics
    - health_checks
